Focus on E2E tests for now
This removes any CI job other than running the actual E2E tests. Given
there are no changes to the underlying codebase, we do not need to
deploy, or run any other checks, to test the E2E tests setup.

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -55,205 +55,202 @@ on:
         default: true
         type: boolean
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
+
 permissions:
   contents: read
   packages: write
 
 jobs:
-  node_build:
-    name: "Node Build 🛠️"
-    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build.yml@v1
-    secrets: inherit
-
-  type_checking:
-    name: "Type check 🔎"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v4.1.7
-
-      - name: Setup Node.js environment
-        uses: actions/setup-node@v4.0.3
-        with:
-          node-version-file: '.node-version'
-          cache: 'npm'
-
-      - name: Installing dependencies
-        run: npm ci
-
-      - name: Typechecking the code
-        run: npm run typecheck
-
-  linting:
-    name: "Linting 🔎"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v4.1.7
-
-      - name: Setup Node.js environment
-        uses: actions/setup-node@v4.0.3
-        with:
-          node-version-file: '.node-version'
-          cache: 'npm'
-
-      - name: Installing dependencies
-        run: npm ci
-
-      - name: Running Lint checks
-        run: npm run lint
-
-      - name: Running shell scripts linting checks
-        run: npm run shellcheck
-
-  helm_lint:
-    name: "Helm config linting 🔎"
-    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
-    strategy:
-      matrix:
-        environments: [ 'dev', 'test', 'preprod', 'prod' ]
-
-  unit_test:
-    name: "Unit testing 🧪"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v4.1.7
-
-      - name: Setup Node.js environment
-        uses: actions/setup-node@v4.0.3
-        with:
-          node-version-file: '.node-version'
-          cache: 'npm'
-
-      - name: Installing dependencies
-        run: npm ci
-
-      - name: Running Unit tests
-        run: npm run test:ci
-
-      - name: Check coverage
-        run: |
-          npx nyc report -t ./coverage --reporter=text --reporter=text-summary
-          npx nyc check-coverage -t ./coverage
-
-  integration_test:
-    name: "Integration testing 🧪"
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        ci_node_index: [ 0, 1, 2, 3 ]
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v4.1.7
-
-      - name: Setup Node.js environment
-        uses: actions/setup-node@v4.0.3
-        with:
-          node-version-file: '.node-version'
-          cache: 'npm'
-
-      - name: Installing dependencies
-        run: npm ci
-
-      - name: Building source
-        run: npm run build
-
-      - name: Downloading test reports from previous runs
-        uses: dawidd6/action-download-artifact@v6
-        with:
-          branch: main
-          if_no_artifact_found: 'ignore'
-          allow_forks: false
-          name: integration-test-junit-xml-reports-.*
-          name_is_regexp: true
-          path: tmp/junit-xml-reports-downloaded
-        continue-on-error: true
-
-      - name: Determining tests splitting by timing
-        uses: r7kamura/split-tests-by-timings@v0
-        id: split-tests
-        with:
-          reports: tmp/junit-xml-reports-downloaded
-          glob: integration_tests/tests/**/*.cy.ts
-          index: ${{ matrix.ci_node_index }}
-          total: 4
-
-      - name: Running Integration tests
-        run: TEST_RUN_ARGS="--spec $(echo ${{ steps.split-tests.outputs.paths }} | sed -E 's/ /,/g')" npm run test:integration
-
-      - name: Fix Cypress JUnit XML reports
-        run: script/fix-cypress-junit-xml
-
-      - name: Store Integration tests reports
-        uses: actions/upload-artifact@v4
-        with:
-          name: integration-test-junit-xml-reports-${{ matrix.ci_node_index }}
-          path: test_results/cypress
-
-      - name: Store Integration tests videos
-        uses: actions/upload-artifact@v4
-        with:
-          name: integration-tests-videos-${{ matrix.ci_node_index }}
-          path: integration_tests/videos
-
-      - name: Store Integration tests screenshots
-        uses: actions/upload-artifact@v4
-        with:
-          name: integration-tests-screenshots-${{ matrix.ci_node_index }}
-          path: integration_tests/screenshots
-
-  build:
-    name: Build docker image from hmpps-github-actions
-    needs:
-      - node_build
-      - linting
-      - helm_lint
-      - unit_test
-      - integration_test
-    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v1
-    with:
-      docker_registry: ${{ inputs.docker_registry || 'ghcr.io' }}
-      registry_org: ${{ inputs.registry_org || 'ministryofjustice' }}
-      additional_docker_tag: ${{ inputs.additional_docker_tag }}
-      push: ${{ inputs.push || true }}
-      docker_multiplatform: ${{ inputs.docker_multiplatform || false }}
-
-  deploy_test:
-    name: Deploy to the test environment
-    needs:
-      - build
-    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature-test/') || startsWith(github.head_ref, 'feature-test/')
-    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v1
-    secrets: inherit
-    with:
-      environment: 'test'
-      app_version: '${{ needs.build.outputs.app_version }}'
-  
-  deploy_dev:
-    name: Deploy to the development environment
-    needs:
-      - build
-    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature-dev-') || startsWith(github.head_ref, 'feature-dev-')
-    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v1
-    secrets: inherit
-    with:
-      environment: 'development'
-      app_version: '${{ needs.build.outputs.app_version }}'
+  #  node_build:
+  #    name: "Node Build 🛠️"
+  #    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build.yml@v1
+  #    secrets: inherit
+  #
+  #  type_checking:
+  #    name: "Type check 🔎"
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - name: Check out code
+  #        uses: actions/checkout@v4.1.7
+  #
+  #      - name: Setup Node.js environment
+  #        uses: actions/setup-node@v4.0.3
+  #        with:
+  #          node-version-file: '.node-version'
+  #          cache: 'npm'
+  #
+  #      - name: Installing dependencies
+  #        run: npm ci
+  #
+  #      - name: Typechecking the code
+  #        run: npm run typecheck
+  #
+  #  linting:
+  #    name: "Linting 🔎"
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - name: Check out code
+  #        uses: actions/checkout@v4.1.7
+  #
+  #      - name: Setup Node.js environment
+  #        uses: actions/setup-node@v4.0.3
+  #        with:
+  #          node-version-file: '.node-version'
+  #          cache: 'npm'
+  #
+  #      - name: Installing dependencies
+  #        run: npm ci
+  #
+  #      - name: Running Lint checks
+  #        run: npm run lint
+  #
+  #      - name: Running shell scripts linting checks
+  #        run: npm run shellcheck
+  #
+  #  unit_test:
+  #    name: "Unit testing 🧪"
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - name: Check out code
+  #        uses: actions/checkout@v4.1.7
+  #
+  #      - name: Setup Node.js environment
+  #        uses: actions/setup-node@v4.0.3
+  #        with:
+  #          node-version-file: '.node-version'
+  #          cache: 'npm'
+  #
+  #      - name: Installing dependencies
+  #        run: npm ci
+  #
+  #      - name: Running Unit tests
+  #        run: npm run test:ci
+  #
+  #      - name: Check coverage
+  #        run: |
+  #          npx nyc report -t ./coverage --reporter=text --reporter=text-summary
+  #          npx nyc check-coverage -t ./coverage
+  #
+  #  integration_test:
+  #    name: "Integration testing 🧪"
+  #    runs-on: ubuntu-latest
+  #    strategy:
+  #      fail-fast: false
+  #      matrix:
+  #        ci_node_index: [ 0, 1, 2, 3 ]
+  #    steps:
+  #      - name: Check out code
+  #        uses: actions/checkout@v4.1.7
+  #
+  #      - name: Setup Node.js environment
+  #        uses: actions/setup-node@v4.0.3
+  #        with:
+  #          node-version-file: '.node-version'
+  #          cache: 'npm'
+  #
+  #      - name: Installing dependencies
+  #        run: npm ci
+  #
+  #      - name: Building source
+  #        run: npm run build
+  #
+  #      - name: Downloading test reports from previous runs
+  #        uses: dawidd6/action-download-artifact@v6
+  #        with:
+  #          branch: main
+  #          if_no_artifact_found: 'ignore'
+  #          allow_forks: false
+  #          name: integration-test-junit-xml-reports-.*
+  #          name_is_regexp: true
+  #          path: tmp/junit-xml-reports-downloaded
+  #        continue-on-error: true
+  #
+  #      - name: Determining tests splitting by timing
+  #        uses: r7kamura/split-tests-by-timings@v0
+  #        id: split-tests
+  #        with:
+  #          reports: tmp/junit-xml-reports-downloaded
+  #          glob: integration_tests/tests/**/*.cy.ts
+  #          index: ${{ matrix.ci_node_index }}
+  #          total: 4
+  #
+  #      - name: Running Integration tests
+  #        run: TEST_RUN_ARGS="--spec $(echo ${{ steps.split-tests.outputs.paths }} | sed -E 's/ /,/g')" npm run test:integration
+  #
+  #      - name: Fix Cypress JUnit XML reports
+  #        run: script/fix-cypress-junit-xml
+  #
+  #      - name: Store Integration tests reports
+  #        uses: actions/upload-artifact@v4
+  #        with:
+  #          name: integration-test-junit-xml-reports-${{ matrix.ci_node_index }}
+  #          path: test_results/cypress
+  #
+  #      - name: Store Integration tests videos
+  #        uses: actions/upload-artifact@v4
+  #        with:
+  #          name: integration-tests-videos-${{ matrix.ci_node_index }}
+  #          path: integration_tests/videos
+  #
+  #      - name: Store Integration tests screenshots
+  #        uses: actions/upload-artifact@v4
+  #        with:
+  #          name: integration-tests-screenshots-${{ matrix.ci_node_index }}
+  #          path: integration_tests/screenshots
+  #
+  #  build:
+  #    name: Build docker image from hmpps-github-actions
+  #    needs:
+  #      - node_build
+  #      #      - linting
+  #      - helm_lint
+  #    #      - unit_test
+  #    #      - integration_test
+  #    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v1
+  #    with:
+  #      docker_registry: ${{ inputs.docker_registry || 'ghcr.io' }}
+  #      registry_org: ${{ inputs.registry_org || 'ministryofjustice' }}
+  #      additional_docker_tag: ${{ inputs.additional_docker_tag }}
+  #      push: ${{ inputs.push || true }}
+  #      docker_multiplatform: ${{ inputs.docker_multiplatform || false }}
+  #
+  #  deploy_test:
+  #    name: Deploy to the test environment
+  #    needs:
+  #      - build
+  #    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature-test/') || startsWith(github.head_ref, 'feature-test/')
+  #    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v1
+  #    secrets: inherit
+  #    with:
+  #      environment: 'test'
+  #      app_version: '${{ needs.build.outputs.app_version }}'
+  #
+  #  deploy_dev:
+  #    name: Deploy to the development environment
+  #    needs:
+  #      - build
+  #    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature-dev-') || startsWith(github.head_ref, 'feature-dev-')
+  #    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v1
+  #    secrets: inherit
+  #    with:
+  #      environment: 'development'
+  #      app_version: '${{ needs.build.outputs.app_version }}'
 
   e2e_test:
     name: "E2E Environment Tests 🧪"
-    needs:
-      - build
-      - deploy_test
-    runs-on: [self-hosted, james-bootstrap] #TODO - change this back to hmpps-github-actions-runner when dependancies have been updated - OR to our own
-    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature-test/') || startsWith(github.head_ref, 'feature-test/')
+    #    needs:
+    #      - build
+    #      - deploy_test
+    runs-on: [ self-hosted, james-bootstrap ] #TODO - change this back to hmpps-github-actions-runner when dependancies have been updated - OR to our own
+    #    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature-test/') || startsWith(github.head_ref, 'feature-test/')
     strategy:
       fail-fast: false
       matrix:
         # TODO - change to 4 where there is more 'oomphf'
-        shard: [1, 2]
+        shard: [ 1, 2 ]
     steps:
       - name: Check out code
         uses: actions/checkout@v4.1.7
@@ -264,9 +261,11 @@ jobs:
           node-version-file: '.node-version'
           cache: 'npm'
 
+      #      - name: Installing dependencies
+      #        if: steps.refresh-cache.outputs.cache-hit != 'true'
+      #        run: NODE_OPTIONS="--max_old_space_size=2048" npm ci --no-audit
       - name: Installing dependencies
-        if: steps.refresh-cache.outputs.cache-hit != 'true'
-        run: NODE_OPTIONS="--max_old_space_size=2048" npm ci --no-audit
+        run: npm i
 
       - name: install playwright
         shell: bash
@@ -275,10 +274,9 @@ jobs:
 
       - name: Run E2E Tests
         env:
-          HMPPS_AUTH_USERNAME: ${{ secrets[format('HMPPS_AUTH_USERNAME_{0}', matrix.shard)] }}
-          HMPPS_AUTH_PASSWORD: ${{ secrets[format('HMPPS_AUTH_PASSWORD_{0}', matrix.shard)] }}
-          HMPPS_AUTH_EMAIL: ${{ secrets[format('HMPPS_AUTH_EMAIL_{0}', matrix.shard)] }}
-          HMPPS_AUTH_NAME: ${{ secrets[format('HMPPS_AUTH_NAME_{0}', matrix.shard)] }}
+          HMPPS_AUTH_USERNAME: ${{ secrets.E2E_USER_DA_AP_USER_TEST_1_USERNAME }}
+          HMPPS_AUTH_PASSWORD: ${{ secrets.E2E_USER_DA_AP_USER_TEST_1_USERNAME }}
+          HMPPS_AUTH_NAME: "TESTY McTESTFACE"
         run: npm run test:e2e:ci -- --shard=${{ matrix.shard }}/2
 
       - name: Upload Playwright Report
@@ -296,7 +294,7 @@ jobs:
           name: test-results-${{ matrix.shard }}
           path: test-results
           retention-days: 30
-# TODO - uncomment when e2e tests run successfully
+  # TODO - uncomment when e2e tests run successfully
   # deploy_preprod:
   #   name: Deploy to pre-production environment
   #   needs: 
